### ISSUE TITLE
Report the bugs, problems you experience

### ISSUE THREAD

**Issue by mbbio** [mbbio/SproutAngio#1]

**Comment by maddemaddi** [comment]
Hi! I have a problem with the second section in your source code, when importing the packages. I get the following error regarding astropy:

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Cell In[7], line 10
>       8 from skimage.measure import label   
>       9 from scipy import ndimage
> ---> 10 from fil_finder import FilFinder2D
>      11 import astropy.units as u
>      12 from skimage.morphology import skeletonize as skeletonize_sci
> 
> File [/opt/anaconda3/envs/SproutAngio/lib/python3.9/site-packages/fil_finder/__init__.py:3](http://localhost:8890/opt/anaconda3/envs/SproutAngio/lib/python3.9/site-packages/fil_finder/__init__.py#line=2)
>       1 # Licensed under an MIT open source license - see LICENSE
> ----> 3 from ._astropy_init import *
>       5 if not _ASTROPY_SETUP_:
>       6     from .filfind_class import fil_finder_2D
> 
> File [/opt/anaconda3/envs/SproutAngio/lib/python3.9/site-packages/fil_finder/_astropy_init.py:21](http://localhost:8890/opt/anaconda3/envs/SproutAngio/lib/python3.9/site-packages/fil_finder/_astropy_init.py#line=20)
>      19 import os
>      20 from warnings import warn
> ---> 21 from astropy.config.configuration import (
>      22     update_default_config,
>      23     ConfigurationDefaultMissingError,
>      24     ConfigurationDefaultMissingWarning)
>      26 # Create the test function for self test
>      27 from astropy.tests.runner import TestRunner
> 
> ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration' ([/opt/anaconda3/envs/SproutAngio/lib/python3.9/site-packages/astropy/config/configuration.py](http://localhost:8890/opt/anaconda3/envs/SproutAngio/lib/python3.9/site-packages/astropy/config/configuration.py))

I tried with astropy versions 5.3.4, 6.0.0, and 6.0.1 but unfortunately it did not work. Do you have any suggestions what I could do?:)

I am using Python3.9.

Kind regards,

Madeleine

**Comment by mbbio** [comment]
Hi Madeleine,
I also tried now with a new install and yes, astropy version 6 causing the error. However, when I tried using:
pip uninstall astropy
and then after the uninstalling,
pip install astropy==5.3.4
it worked for me. You tried 5.3.4, but is it possible that you did not do uninstalling and somehow it did not properly uninstall?
Other than this, maybe you can try other 5.3 versions as well: 5.3.3 or 5.3.2.
Please let me know if this solves the issue. I am planning to do an update around the end of April to improve the pipeline and solve possible issues like this because of the library updates.
Kind regards,
Musti

**Comment by ahsusohail** [comment]
I am getting the following error message when I run the second section of Sprout Angio main:

‘ForwardRef._evaluate() missing 1 required keyword-only argument: ‘recursive_guard’'

Would you be able to help figuring out how I can fix this on Jupyter?
