### ISSUE TITLE
‘ForwardRef._evaluate() missing 1 required keyword-only argument: ‘recursive_guard’’

### ISSUE THREAD

**Issue by ahsusohail** [mbbio/SproutAngio#2]
I am getting the following error message when I run the second section of Sprout Angio main: 

‘ForwardRef._evaluate() missing 1 required keyword-only argument: ‘recursive_guard’'

Would you be able to help figuring out how I can fix this on Jupyter?

**Comment by mbbio** [comment]
Hi, can you please write your python version? 
You can check it on jupyter using

import sys
sys.version

**Comment by ahsusohail** [comment]
python version is 3.12.4

**Comment by ahsusohail** [comment]
I was able to fix the issue by converting to python version 3.12.3
